wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-01.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-02.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-03.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-04.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-05.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-06.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-07.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-08.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-09.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-10.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-11.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-12.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-13.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-14.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-15.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-16.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-17.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-18.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-19.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-20.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-21.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-22.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-23.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-24.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-25.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-26.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-27.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-28.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-29.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-30.csv
wget https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2023-09-31.csv
